apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django-container
        image: juvobest/django-devops-app:latest
        ports:
        - containerPort: 8000
