apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: devops-app
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8090       # Expose 8090
      targetPort: 8090 # Match container port
  type: LoadBalancer
